### PR TITLE
Test script: cycle tab

### PR DESCRIPTION
**Pull request by gabalafou**

### CODE REVIEW

**Comment by gabalafou** [comment]
Here are some screenshots of how the test failures look in Playwright with this additional test.

image

image

If you watch the video that Playwright produces, you can actually see Playwright tabbing across the JupyterLab UI wherever it lands on elements that have visible focus, and then it just tabs off to nowhere.

**Comment by trallard** [comment]
@trallard check in GitPod

**Review by trallard — APPROVED** [review]
LGTM - managed to run this on Gitpod and all seems to be working ok 👍🏽 

is there any more work needed atm?

**Comment by gabalafou** [comment]
> is there any more work needed atm?

Nope. All good to merge. I simply forgot to take the PR out of draft mode earlier.

**Comment by gabalafou** [comment]
I just merged this into the main branch. So next step is... use the same branch of this PR (`a11y-test-no-keyboard-trap`) to open a new pull request against `jupyter/accessibility`?

**Comment by trallard** [comment]
Pull Request from this repo `master` into `jupyter/accessibility master` to avoid having diverging histories 😉

**Comment by gabalafou** [comment]
@trallard like this? https://github.com/jupyter/accessibility/pull/92

**Comment by trallard** [comment]
Yes - we need to merge #5 before merging to avoid issues with the GH actions

**Comment by trallard** [comment]
Now that #5  is merged we can mark your PR as ready 🚀

**Pull request merged**
